### ISSUE TITLE
Could not get the examples to display the charts

### ISSUE THREAD

**Issue by AlanApter** [sugarcrm/sucrose#4]
I ran the following commands on debian wheezy, with npm version 3.9.6, node version v4.4.5, Debian 8 (jessie) to get it working:

```
git clone https://github.com/sugarcrm/sucrose
cd sucrose/
npm i --save-dev
make clean
make all
cd examples/
npm i --save-dev
make clean
make all

```

The front page displayed information, however when I clicked on the charts tabs, I couldn't get any of the images to display. The javascript console displayed the following error:

> jQuery.Deferred exception: d.size is not a function TypeError: d.size is not a function
>     at u (http://localhost/sucrose/examples/js/jquerymy.min.js:4:7677)
>     at Object.<anonymous> (http://localhost/sucrose/examples/js/jquerymy.min.js:4:17014)
>     at iterateOverObject (http://localhost/sucrose/examples/js/lib.min.js:19:4508)
>     at Function.each (http://localhost/sucrose/examples/js/lib.min.js:19:27673)
>     at w (http://localhost/sucrose/examples/js/jquerymy.min.js:4:16968)
>     at r (http://localhost/sucrose/examples/js/jquerymy.min.js:4:16685)
>     at g (http://localhost/sucrose/examples/js/jquerymy.min.js:4:14070)
>     at r.I (http://localhost/sucrose/examples/js/jquerymy.min.js:4:18992)
>     at r.a.fn.my (http://localhost/sucrose/examples/js/jquerymy.min.js:5:11104)
>     at Object.loadForm (http://localhost/sucrose/examples/js/app.min.js:4:23353) undefined

**Comment by hhrogersii** [comment]
@AlanApter , sorry for the delay in resolving this. Finally sorted out errors in the Makefiles (https://github.com/sugarcrm/sucrose/pull/36).  I've updated the root README.md with instructions for setting up the local examples application (e.g., make examples-dev). Also, if you go to http://sucrose.io, configure a chart in the editor, then click the download package button in the chart panel tab, it will download a zip package containing all files to run the chart as configured as a stand alone page.
