### ISSUE TITLE
No examples in http://sucrose.io/ as stated in README.md#Features (EOM)

### ISSUE THREAD

**Issue by gooddadmike** [sugarcrm/sucrose#5]

**Comment by mmarum-sugarcrm** [comment]
Hi Mike,

Sorry for late response. The links to the examples are at the top right of the page.

![image](https://cloud.githubusercontent.com/assets/2186217/25346651/27d197ea-28e6-11e7-97a1-ab1e9e40efab.png)

**Comment by hhrogersii** [comment]
I've updated the README files with instructions for running make commands to set up the examples locally. I also updated the http://sucrose.io homepage with direct links to the chart examples.
