### ISSUE TITLE
Gauge Chart Unable to Hide Labels

### ISSUE THREAD

**Issue by tsummerer** [sugarcrm/sucrose#51]
The Gauge chart contains a `showLabel` setting, but it is not implemented. 

This becomes troublesome if a chart uses large numbers and they run into each other. 

Screenshot:
![image](https://user-images.githubusercontent.com/3300497/42114923-81b484e2-7bb6-11e8-8d45-3f719e29f8f4.png)

Demo Data:
```json
{
  "properties": {
    "title": "Sales Goal",
    "value": 211000,
    "values": [],
    "colorLength": 4
  },
  "data": [
    {
      "key": "Goal",
      "value": 200000,
      "seriesIndex": 0,
      "total": 200000
    },
    {
      "key": "Excess",
      "value": 11000,
      "color": "#2CA02C",
      "seriesIndex": 1,
      "total": 11000
    }
  ]
}
```

**Comment by sidharthjonnala-sugarcrm** [comment]
Closing this issue, because we are deprecating and archiving this repository.
